server:
  port: 8090

spring:
  application:
    name: Aug7_MultipleDBConnection
  oracle:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: Eidiko
      password: sarasu10
      driver-class-name: oracle.jdbc.OracleDriver

  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/Eidiko
      username: root
      password: sarasu10
      driver-class-name: com.mysql.cj.jdbc.Driver